# Generated by Django 5.0.6 on 2026-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agenttoken_can_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='lookup_id',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='agenttoken',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Fine-grained permission scopes'),
        ),
    ]
