# Generated by Django 5.0.6 on 2026-07-31 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agenttoken_can_auto_approve'),
        ('artifacts', '0003_alter_artifact_lifecycle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_data', models.JSONField(default=list, help_text='ADM Block[] — the canonical document during editing.')),
                ('commit_msg_hint', models.CharField(blank=True, max_length=255)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='artifacts.artifact')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_drafts', to='accounts.principal')),
                ('participants', models.ManyToManyField(blank=True, help_text='Principals who have contributed edits to this draft.', related_name='draft_participations', to='accounts.principal')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
